language: go

env:
  global:
    # BAR
    - secure: cwhtDV5cYNQykyc5MpXfWqPdes35pCS6nnU5MfqZ5fwmxubLpOhWtcivEjOZqErBDRTivDa+J2xmdur9Ab9VGL9RuTMwthW5W8+LdIcz4Oba45ExV7Dp9f/OIRXVIllmfhxWdT971/Duc5QYWfOs7whqzFdlt24BCousAXbM+swqq6EUrQC/G+az7HGZF6TmZ0JthtOpXgXoQTgkLSvs3+VwKfMfH3ByPWkI6L4infhhP24Y6iYdzTczY15xNlneUGRHWxF1+vV3L+3KmufRpwddE1m4lzBgspxv4EJMI5X/Pu8/PzAenVbS8+fiw+fT+pLQ7/uwVPVp68mI6N6UI1LEekfPVBcGyAvis5ncB/yLXgtK1rgs8taf/wIuNTq9NNrHY092akZI9EpoiVMlDTX9XEp0Gnqebw91eBNZCLTBoBI6S19u3GxhcOD5AgKCBlHn9ZS+R28j6f5j0v6GXrSHymzAGSuBPpoSxDQPrClcmYHXIEzcDvd7zQF9mCWBFDdw/fa2akp1pRk53YkjRQ9pro638F88IEkP7gZepdmBfQEekKlpnqrimKgN1wEEBx62XQHL9pW9arnCDovGUTRc8DasI5twlhBPP/vEvf9CdMMk5YEQT2rkDfYGQLt+17A9g7HQuoPyMTvHsQHR3HydWZUZFO0qv8h0Q9aCMss=
